force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <formula>CreatedBy.Department</formula>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Details__c.field-meta.xml
<CustomField>
    <fullName>Task_Details__c</fullName>
    <label>Task Details</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Upload_Document__c.field-meta.xml
<CustomField>
    <fullName>Upload_Document__c</fullName>
    <label>Upload Document</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/tasDetailsController.cls
public class tasDetailsController {
    @AuraEnabled(cacheable=true)
  public static List<Task__c> getTasks() {
    return [
      SELECT
        Id,
        Name,
        Employee_Name__c,
        Task_Name__c,
        Task_Details__c,
        Upload_Document__c,
        Approval_Status__c,
        Domain__c,
        CreatedDate
      FROM Task__c
      WHERE Task_Name__c!= Null
      WITH SECURITY_ENFORCED
      ORDER BY  Name DESC
    ];
    }
}