force-app/main/default/objects/Attendence_Details__c/Attendence_Details__c.object-meta.xml
<CustomObject>
    <label>Attendence Details</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Attendence Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendence Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendence_Details__c/fields/CheckInTime__c.field-meta.xml
<CustomField>
    <fullName>CheckInTime__c</fullName>
    <label>CheckInTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/CheckOutTime__c.field-meta.xml
<CustomField>
    <fullName>CheckOutTime__c</fullName>
    <label>CheckOutTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Requests No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#FFFF66</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#33FF33</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/checkInController.cls
public with sharing class checkInController {
    @AuraEnabled(cacheable=false)
    public static Attendence_Details__c checkIn(String recordId) {
        try {
            // Check if the user is already checked in
            List<Attendence_Details__c> existingRecords = [
                SELECT Id,CheckInTime__c,CheckOutTime__c
                FROM Attendence_Details__c
                WHERE CheckOutTime__c = null
                AND CreatedById = :recordId  
            ];
            
            if (!existingRecords.isEmpty()) {
                // User is already checked in
                throw new AuraHandledException('You are already checked in.');
            } else {
                // Proceed with check-in
                Attendence_Details__c att = new Attendence_Details__c();
                att.CheckInTime__c = DateTime.now();
                insert att;
                return att;
            }
        } catch (Exception e) {
            System.debug('Unable to update the records: ' + e.getMessage());
            throw new AuraHandledException('Unable to update the records: ' + e.getMessage());
        }
    }


    @AuraEnabled (cacheable=true)
  public static List<Attendence_Details__c> getAttendenceDetails(String userId) {
    return [
      SELECT Id,
        CheckOutTime__c,CreatedById
      FROM Attendence_Details__c
      WHERE CheckOutTime__c = Null AND CreatedById = :userId
      WITH SECURITY_ENFORCED
    ];
    }

    @AuraEnabled(cacheable=true)
    public static Boolean hasApprovedLeave(String userId) {
        Date today = Date.today();
        List<Leave_Request__c> leaveRequests = [
            SELECT Id FROM Leave_Request__c 
            WHERE CreatedById = :userId 
            AND Approval_Status__c = 'Approved' 
            AND Start_Date__c <= :today 
            AND End_Date__c >= :today
        ];
        return leaveRequests.size() > 0;
    }
}