force-app/main/default/objects/Attendence_Details__c/Attendence_Details__c.object-meta.xml
<CustomObject>
    <label>Attendence Details</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Attendence Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendence Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendence_Details__c/fields/CheckInTime__c.field-meta.xml
<CustomField>
    <fullName>CheckInTime__c</fullName>
    <label>CheckInTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/CheckOutTime__c.field-meta.xml
<CustomField>
    <fullName>CheckOutTime__c</fullName>
    <label>CheckOutTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>CreatedBy.FirstName +&apos; &apos; + CreatedBy.LastName</formula>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/Working_Hours__c.field-meta.xml
<CustomField>
    <fullName>Working_Hours__c</fullName>
    <formula>(FLOOR((CheckOutTime__c - CheckInTime__c)*24))
+
(((((CheckOutTime__c - CheckInTime__c)*24)-FLOOR((CheckOutTime__c - CheckInTime__c)*24))*60)/100)</formula>
    <label>Working Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/attendenceDetailsController.cls
public class attendenceDetailsController {
  @AuraEnabled(cacheable=true)
  public static List<Attendence_Details__c> getAttendence() {
    return [
      SELECT
        Id,  
        Name,
        Employee_Name__c,
        CheckInTime__c,
        CheckOutTime__c,
        Working_Hours__c,
        Domain__c
      FROM Attendence_Details__c
      WITH SECURITY_ENFORCED
      ORDER BY CheckInTime__c DESC
    ];
    }
}