force-app/main/default/objects/Attendence_Details__c/Attendence_Details__c.object-meta.xml
<CustomObject>
    <label>Attendence Details</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Attendence Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendence Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendence_Details__c/fields/CheckInTime__c.field-meta.xml
<CustomField>
    <fullName>CheckInTime__c</fullName>
    <label>CheckInTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/CheckOutTime__c.field-meta.xml
<CustomField>
    <fullName>CheckOutTime__c</fullName>
    <label>CheckOutTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>CreatedBy.FirstName +&apos; &apos; + CreatedBy.LastName</formula>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendence_Details__c/fields/Working_Hours__c.field-meta.xml
<CustomField>
    <fullName>Working_Hours__c</fullName>
    <formula>(FLOOR((CheckOutTime__c - CheckInTime__c)*24))
+
(((((CheckOutTime__c - CheckInTime__c)*24)-FLOOR((CheckOutTime__c - CheckInTime__c)*24))*60)/100)</formula>
    <label>Working Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Requests No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#FFFF66</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#33FF33</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Count_Leave_Day__c.field-meta.xml
<CustomField>
    <fullName>Count_Leave_Day__c</fullName>
    <formula>End_Date__c - Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Count Leave Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>CreatedBy.FirstName +&apos; &apos;+  CreatedBy.LastName</formula>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Reason_For_Leave__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Leave__c</fullName>
    <label>Reason For Leave</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <formula>CreatedBy.Department</formula>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Details__c.field-meta.xml
<CustomField>
    <fullName>Task_Details__c</fullName>
    <label>Task Details</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GlobalReportsController.cls
public class GlobalReportsController {
    @AuraEnabled(cacheable=true)
    public static List<Map<String,Object>>  getGlobalReports() {
        Map<Date,Map<String,Object>> DateToRecordMap = new Map<Date,Map<String,Object>>();
        
        // Query Attendance Details 
        List<Attendence_Details__c> attendenceDetails = [SELECT Id, Employee_Name__c, Domain__c, CheckInTime__c, CheckOutTime__c, Working_Hours__c, CreatedDate
                                              FROM Attendence_Details__c
                                               
                                              ORDER BY CreatedDate DESC];
        for (Attendence_Details__c record : attendenceDetails) {
             Date recordDate = record.CreatedDate.date(); 
             if(!DateToRecordMap.containsKey(recordDate)){
                DateToRecordMap.put(recordDate,new Map<String,Object>());
             } 
            Map<String,Object> margedRecord = DateToRecordMap.get(recordDate);
            margedRecord.put('AttendenceDetails',record);
        }

        // Query Task Details
        List<Task__c> taskDetails = [SELECT Id, Task_Name__c, Task_Details__c,Employee_Name__c, Domain__c, Approval_Status__c, CreatedDate
                                  FROM Task__c
                            
                                  ORDER BY CreatedDate DESC];
        for (Task__c record : taskDetails) {
             
            Date recordDate = record.CreatedDate.date(); 
             if(!DateToRecordMap.containsKey(recordDate)){
                DateToRecordMap.put(recordDate,new Map<String,Object>());
             }
            Map<String,Object> margedRecord = DateToRecordMap.get(recordDate);
            margedRecord.put('TaskDetails',record);
        }

        // Query Leave Requests
        List<Leave_Request__c> leaveRequests = [SELECT Id, Leave_Type__c, Reason_For_Leave__c,Start_Date__c,End_Date__c, Count_Leave_Day__c,Employee_Name__c, Approval_Status__c, CreatedDate
                                                   FROM Leave_Request__c
                                                    
                                                   ORDER BY CreatedDate DESC];
        for (Leave_Request__c record : leaveRequests) { 
            Date recordDate = record.CreatedDate.date(); 
             if(!DateToRecordMap.containsKey(recordDate)){
                DateToRecordMap.put(recordDate,new Map<String,Object>());
             }
            Map<String,Object> margedRecord = DateToRecordMap.get(recordDate);
            margedRecord.put('LeaveDetails',record);
        }

        return new List<Map<String, Object>>(DateToRecordMap.values());
    }


    public class WrapData {
        @AuraEnabled public String xAxis;
        @AuraEnabled public Integer yAxisForAttendence = 0;
        @AuraEnabled public Integer yAxisForTask = 0;
        @AuraEnabled public Integer yAxisForLeave = 0;
    }

    @AuraEnabled(Cacheable=true)
    public static List<WrapData> getChartValue() {
        Map<String,WrapData> dataMap = new Map<String,WrapData>();

         List<AggregateResult> attendenceResults = [SELECT CALENDAR_MONTH(CreatedDate) month, COUNT(Id) cnt
                                                        FROM Attendence_Details__c GROUP BY CALENDAR_MONTH(CreatedDate)];
        for(AggregateResult ar:attendenceResults){
            String month = String.valueOf(ar.get('month'));
            Integer count = Integer.valueOf(ar.get('cnt'));
            if(!dataMap.containsKey(month)){
                dataMap.put(month, new WrapData());
                dataMap.get(month).xAxis = month;
            }
            dataMap.get(month).yAxisForAttendence = count;
        }

        List<AggregateResult> taskResults = [SELECT CALENDAR_MONTH(CreatedDate) month, COUNT(Id) cnt 
                                                FROM Task__c GROUP BY CALENDAR_MONTH(CreatedDate)];
        for(AggregateResult ar:taskResults){
            String month = String.valueOf(ar.get('month'));
            Integer count = Integer.valueOf(ar.get('cnt'));
            if(!dataMap.containsKey(month)){
                dataMap.put(month, new WrapData());
                dataMap.get(month).xAxis = month;
            }
            dataMap.get(month).yAxisForTask = count;
        }
        List<AggregateResult> leaveResults = [SELECT CALENDAR_MONTH(CreatedDate) month, COUNT(Id) cnt
                                                FROM Leave_Request__c GROUP BY CALENDAR_MONTH(CreatedDate)];
        for(AggregateResult ar:leaveResults){
            String month = String.valueOf(ar.get('month'));
            Integer count = Integer.valueOf(ar.get('cnt'));
            if(!dataMap.containsKey(month)){
                dataMap.put(month, new WrapData());
                dataMap.get(month).xAxis = month;
            }
            dataMap.get(month).yAxisForLeave = count;
        }
        return dataMap.values();
    }
}