force-app/main/default/objects/Attendence__c/Attendence__c.object-meta.xml
<CustomObject>
    <label>Attendence</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendence</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendence__c/fields/Date_Of_Joining__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Joining__c</fullName>
    <label>Date Of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendence__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Science/Data Analyst</fullName>
            </value>
            <value>
                <fullName>Java(Full Stack)</fullName>
            </value>
            <value>
                <fullName>Mern Stack</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendence__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <label>Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendence__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/employeeDetailsController.cls
public with sharing class employeeDetailsController {
    @AuraEnabled(cacheable=true)
    public static List<Attendence__c> getEmployees() {
      return [
        SELECT
          Id,
          Name,
          Employee_ID__c,
          Email_Id__c,
          Domain__c,
          Date_Of_Joining__c
        FROM Attendence__c
        WHERE Employee_ID__c!= Null
        WITH SECURITY_ENFORCED
      ];
      }
}